version: "3"
services:
  mapping-db:
    image: postgres:15
    container_name: mapping-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=mapping
      - POSTGRES_USER=mapping
      - POSTGRES_DB=mapping
