server:
  shutdown: immediate
  port: 8084

management.endpoint:
  health.cache.time-to-live: 0
  info.cache.time-to-live: 0

api:
  base:
    url:
      oauth: http://localhost:9090/auth

spring:
  devtools:
    add-properties: true

  flyway:
    url: jdbc:postgresql://localhost:5432/mapping?sslmode=prefer
    user: mapping
    password: mapping

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/mapping?sslmode=prefer
    username: mapping
    password: mapping
    properties:
      sslMode: DISABLE
      sslRootCert:
